create extension if not exists pgcrypto;

create table if not exists public.user_profiles (
    id bigint generated by default as identity primary key,
    email text not null unique,
    username text not null,
    first_name text not null,
    last_name text not null,
    role text not null default 'STUDENT',
    phone_number text,
    profile_image bytea,
    profile_image_name text,
    profile_image_content_type text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.report_items (
    id bigint generated by default as identity primary key,
    user_id bigint,
    email text not null,
    title text not null,
    description text not null,
    location text not null,
    image_name text,
    status text not null default 'Pending',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    report_id bigint,
    recipient_user_id bigint,
    recipient_email text,
    recipient_role text not null,
    title text not null,
    message text not null,
    is_read boolean not null default false,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.user_profiles add column if not exists role text not null default 'STUDENT';
alter table public.user_profiles add column if not exists profile_image bytea;
alter table public.user_profiles add column if not exists profile_image_name text;
alter table public.user_profiles add column if not exists profile_image_content_type text;
alter table public.report_items add column if not exists description text not null default 'No description provided.';
alter table public.report_items add column if not exists location text not null default 'Unspecified location';
alter table public.report_items add column if not exists image_name text;
alter table public.report_items add column if not exists user_id bigint;
alter table public.notifications add column if not exists report_id bigint;
alter table public.notifications add column if not exists recipient_user_id bigint;
alter table public.notifications add column if not exists recipient_email text;
alter table public.notifications add column if not exists recipient_role text not null default 'USER';
alter table public.notifications add column if not exists title text not null default 'Notification';
alter table public.notifications add column if not exists message text not null default 'Message';
alter table public.notifications add column if not exists is_read boolean not null default false;
alter table public.notifications add column if not exists created_at timestamptz not null default timezone('utc', now());

update public.notifications n
set recipient_user_id = r.user_id
from public.report_items r
where n.recipient_user_id is null
    and n.report_id = r.id
    and r.user_id is not null;

update public.notifications n
set recipient_user_id = p.id
from public.user_profiles p
where n.recipient_user_id is null
    and n.recipient_email is not null
    and lower(n.recipient_email) = lower(p.email);

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'report_items_status_check'
    ) then
        alter table public.report_items
            add constraint report_items_status_check
            check (status in ('Pending', 'In-Progress', 'Fixed', 'Cancelled'));
    end if;
end $$;

update public.report_items r
set user_id = p.id
from public.user_profiles p
where r.user_id is null
  and lower(r.email) = lower(p.email);

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'report_items_user_id_fkey'
    ) then
        alter table public.report_items
            add constraint report_items_user_id_fkey
            foreign key (user_id) references public.user_profiles(id)
            on delete set null;
    end if;
end $$;

create index if not exists idx_report_items_user_id on public.report_items(user_id);

drop view if exists public.user_dashboard_summary;

create view public.user_dashboard_summary as
select
    user_id,
    max(email) as email,
    count(*)::bigint as total_reports,
    count(*) filter (where status = 'Fixed')::bigint as resolved_reports,
    count(*) filter (where status in ('Pending', 'In-Progress'))::bigint as alerts_count,
    max(created_at) as last_report_at
from public.report_items
where user_id is not null
group by user_id;

create or replace function public.set_updated_at_timestamp()
returns trigger as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at_timestamp();

drop trigger if exists trg_report_items_updated_at on public.report_items;
create trigger trg_report_items_updated_at
before update on public.report_items
for each row execute function public.set_updated_at_timestamp();

alter table public.user_profiles enable row level security;
alter table public.report_items enable row level security;
alter table public.notifications enable row level security;

drop policy if exists user_profiles_select on public.user_profiles;
drop policy if exists user_profiles_insert on public.user_profiles;
drop policy if exists user_profiles_update on public.user_profiles;

drop policy if exists report_items_select on public.report_items;
drop policy if exists report_items_insert on public.report_items;
drop policy if exists report_items_update on public.report_items;
drop policy if exists report_items_delete on public.report_items;
drop policy if exists notifications_select on public.notifications;
drop policy if exists notifications_insert on public.notifications;
drop policy if exists notifications_update on public.notifications;
drop policy if exists notifications_delete on public.notifications;

create policy user_profiles_select on public.user_profiles
for select using (true);

create policy user_profiles_insert on public.user_profiles
for insert with check (true);

create policy user_profiles_update on public.user_profiles
for update using (true) with check (true);

create policy report_items_select on public.report_items
for select using (true);

create policy report_items_insert on public.report_items
for insert with check (true);

create policy report_items_update on public.report_items
for update using (true) with check (true);

create policy report_items_delete on public.report_items
for delete using (true);

create policy notifications_select on public.notifications
for select using (true);

create policy notifications_insert on public.notifications
for insert with check (true);

create policy notifications_update on public.notifications
for update using (true) with check (true);

create policy notifications_delete on public.notifications
for delete using (true);
